### ISSUE TITLE
Separate English version might better be integrated into German one

### ISSUE THREAD

**Issue by aljoshakoecher** [hsu-aut/IndustrialStandard-ODP-VDI2860#10]
Since when is there an English version? I think we should drop the English version and add the English terms as English `rdfs:label`s.
The standard only defines a German version. I think it's not up to us to create an English version, but providing in unofficial translation as labels is okay for my taste.
No matter how we do it, we need to have a consistent way of doing it.

@jannikreisberg, @jelenito: What do you think?

**Comment by jelenito** [comment]
I agree with you. In my opinion, we should introduce language tags (en/de) and add  `rdfs:label`s with English translations.

**Comment by jannikreisberg** [comment]
True! I will add it to one OWL file and then upload the new version including both with rdfs:label as I did the English translation.

**Comment by jannikreisberg** [comment]
Sometimes you directy should do what you planned to do: Englisch & German label is updated in "VDI2860.OWL" at master branch.
